### ISSUE TITLE
Unexpected attribute properties for pysam.AlignedSegment

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#11]
Hi Chris,

I am getting the following error on a bam file when running `./phyloscanner_make_trees.py `

```
Unexpected attribute properties for pysam.AlignedSegment
 M03475:62:000000000-B2RNP:1:2110:11349:14877	165	0	301	0	None	0	301	8	ATGCCGTC	array('B', [35, 35, 37, 37, 37, 34, 35, 35])	[('RG', 'ZY6QANZF1GE'), ('ZA', '<&;0;0;;2;12S7M1I77M;2T6C75><@;0;0;;0;;>')] 
Quitting
```
I just emailed you a sample of the reads.
Many thanks,
Damien

**Comment by ChrisHIV** [comment]
Hi Damien, I'm on holiday at the moment and at a conference next week; I'll try to find time to look at it during the conference. Cheers

**Comment by damientully** [comment]
Great thanks Chris!

**Comment by ChrisHIV** [comment]
Hi Damien, thanks for catching that. Pull the code and try again.

**Comment by damientully** [comment]
Hi Chris,

Appears to be working now.

Thanks!
Damien
