### ISSUE TITLE
Issue running analyse trees

### ISSUE THREAD

**Issue by KELEONUCSF** [BDI-pathogens/phyloscanner#12]
Hi All,

I'm having a problem running the analyse_trees part of phyloscanner. The make_trees script worked fine, but now I keep receiving this message:

Error: length(lims) == 2 is not TRUE
Execution halted

when I try to execute the phyloscanner_analyse_trees.r script. Any help would be greatly appreciated!

**Comment by twoseventwo** [comment]
Hi,

Could you let me know which command line options you used to run it, and also re-run it with --verbose and attach the screen output?

Thanks, Matthew

**Comment by KELEONUCSF** [comment]
Hi Matthew,



I really appreciate the fast response! I'm really excited about your tool, so I really want to get it working!


My command line:


/Users/kristofferleon/Documents/Apps_Files/phyloscanner-master/phyloscanner_analyse_trees.R /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree. Catalonia_CSF_Phyloscanner s,0 --outgroupName Enterovirus.CATALONIA_14L_S14_Assembly_Contig_Assembly_consensus_sequence_extraction --multifurcationThreshold g


Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1_to_112.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1008_to_1116.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1116_to_1231.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_112_to_228.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1231_to_1352.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1352_to_1472.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1472_to_1588.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1588_to_1714.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1714_to_1853.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1853_to_1960.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_1960_to_2069.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2069_to_2172.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2172_to_2274.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2274_to_2377.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_228_to_332.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2377_to_2483.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2483_to_2591.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2591_to_2709.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2709_to_2818.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2818_to_2946.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_2946_to_3066.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3066_to_3181.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3181_to_3329.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_332_to_455.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3329_to_3461.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3461_to_3566.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3566_to_3675.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3675_to_3788.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3788_to_3898.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_3898_to_4024.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4024_to_4137.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4137_to_4262.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4262_to_4379.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4379_to_4483.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4483_to_4596.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_455_to_564.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4596_to_4706.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4706_to_4821.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4821_to_4932.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_4932_to_5041.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5041_to_5147.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5147_to_5260.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5260_to_5367.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5367_to_5472.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5472_to_5580.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5580_to_5696.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_564_to_676.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5696_to_5801.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5801_to_5911.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_5911_to_6014.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6014_to_6131.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6131_to_6251.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6251_to_6382.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6382_to_6494.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6494_to_6600.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6600_to_6704.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6704_to_6819.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_676_to_776.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6819_to_6925.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_6925_to_7030.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7030_to_7133.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7133_to_7262.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7262_to_7388.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7388_to_7496.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7496_to_7606.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7606_to_7712.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7712_to_7824.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_776_to_899.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7824_to_7954.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_7954_to_8083.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_8083_to_8189.tree

Reading tree file /Users/kristofferleon/Documents/UCSF/Wilson_Lab/Catalonia/SAM_files/RAxMLfiles/RAxML_bestTree.InWindow_899_to_1008.tree

Processing tree for suffix InWindow_1_to_112.

Processing tree for suffix InWindow_1008_to_1116.

Processing tree for suffix InWindow_1116_to_1231.

Processing tree for suffix InWindow_112_to_228.

Processing tree for suffix InWindow_1231_to_1352.

Processing tree for suffix InWindow_1352_to_1472.

Processing tree for suffix InWindow_1472_to_1588.

Processing tree for suffix InWindow_1588_to_1714.

Processing tree for suffix InWindow_1714_to_1853.

Processing tree for suffix InWindow_1853_to_1960.

Processing tree for suffix InWindow_1960_to_2069.

Processing tree for suffix InWindow_2069_to_2172.

Processing tree for suffix InWindow_2172_to_2274.

Processing tree for suffix InWindow_2274_to_2377.

Processing tree for suffix InWindow_228_to_332.

Processing tree for suffix InWindow_2377_to_2483.

Processing tree for suffix InWindow_2483_to_2591.

Processing tree for suffix InWindow_2591_to_2709.

Processing tree for suffix InWindow_2709_to_2818.

Processing tree for suffix InWindow_2818_to_2946.

Processing tree for suffix InWindow_2946_to_3066.

Processing tree for suffix InWindow_3066_to_3181.

Processing tree for suffix InWindow_3181_to_3329.

Processing tree for suffix InWindow_332_to_455.

Processing tree for suffix InWindow_3329_to_3461.

Processing tree for suffix InWindow_3461_to_3566.

Processing tree for suffix InWindow_3566_to_3675.

Processing tree for suffix InWindow_3675_to_3788.

Processing tree for suffix InWindow_3788_to_3898.

Processing tree for suffix InWindow_3898_to_4024.

Processing tree for suffix InWindow_4024_to_4137.

Processing tree for suffix InWindow_4137_to_4262.

Processing tree for suffix InWindow_4262_to_4379.

Processing tree for suffix InWindow_4379_to_4483.

Processing tree for suffix InWindow_4483_to_4596.

Processing tree for suffix InWindow_455_to_564.

Processing tree for suffix InWindow_4596_to_4706.

Processing tree for suffix InWindow_4706_to_4821.

Processing tree for suffix InWindow_4821_to_4932.

Processing tree for suffix InWindow_4932_to_5041.

Processing tree for suffix InWindow_5041_to_5147.

Processing tree for suffix InWindow_5147_to_5260.

Processing tree for suffix InWindow_5260_to_5367.

Processing tree for suffix InWindow_5367_to_5472.

Processing tree for suffix InWindow_5472_to_5580.

Processing tree for suffix InWindow_5580_to_5696.

Processing tree for suffix InWindow_564_to_676.

Processing tree for suffix InWindow_5696_to_5801.

Processing tree for suffix InWindow_5801_to_5911.

Processing tree for suffix InWindow_5911_to_6014.

Processing tree for suffix InWindow_6014_to_6131.

Processing tree for suffix InWindow_6131_to_6251.

Processing tree for suffix InWindow_6251_to_6382.

Processing tree for suffix InWindow_6382_to_6494.

Processing tree for suffix InWindow_6494_to_6600.

Processing tree for suffix InWindow_6600_to_6704.

Processing tree for suffix InWindow_6704_to_6819.

Processing tree for suffix InWindow_676_to_776.

Processing tree for suffix InWindow_6819_to_6925.

Processing tree for suffix InWindow_6925_to_7030.

Processing tree for suffix InWindow_7030_to_7133.

Processing tree for suffix InWindow_7133_to_7262.

Processing tree for suffix InWindow_7262_to_7388.

Processing tree for suffix InWindow_7388_to_7496.

Processing tree for suffix InWindow_7496_to_7606.

Processing tree for suffix InWindow_7606_to_7712.

Processing tree for suffix InWindow_7712_to_7824.

Processing tree for suffix InWindow_776_to_899.

Processing tree for suffix InWindow_7824_to_7954.

Processing tree for suffix InWindow_7954_to_8083.

Processing tree for suffix InWindow_8083_to_8189.

Processing tree for suffix InWindow_899_to_1008.

Gathering host IDs...

Reconstructing internal node hosts on tree suffix InWindow_1_to_112

Getting tip read counts...

Identifying tips with host...

Finding list of hosts...

Finding tips for each host...

Finding MRCAs for each host...

Reconstructing internal node hosts with the Sankoff algorithm...

Calculating node costs...

Building full cost matrix...

  |==================================================| 100%

Reconstructing...

Identifying split hosts...

Drawing PDF tree...

Error: length(lims) == 2 is not TRUE

Execution halted


Thanks,


Kristoffer


________________________________

**Comment by twoseventwo** [comment]
Hi Kristoffer,

No worries, we need to know about bugs!

I haven't worked out exactly what's wrong yet - as a workaround, try running with -tn to get Nexus rather than PDF trees, since it's the latter that is causing this.

What version of R are you using?

Thanks, Matthew

**Comment by twoseventwo** [comment]
It would be good to know what went wrong - is the data sensitive, or could you send me a tree? (Just one tree should do, I think.)

**Comment by KELEONUCSF** [comment]
[ProcessedTree_Catalonia_CSF_Phyloscanner_InWindow_1_to_112.txt](https://github.com/BDI-pathogens/phyloscanner/files/1181348/ProcessedTree_Catalonia_CSF_Phyloscanner_InWindow_1_to_112.txt)

**Comment by KELEONUCSF** [comment]
The tree should be posted above!

**Comment by KELEONUCSF** [comment]
[RAxML_bestTree.InWindow_1_to_112.txt](https://github.com/BDI-pathogens/phyloscanner/files/1181367/RAxML_bestTree.InWindow_1_to_112.txt)

Realised that you might have the meant the tree used for input instead of the output. This should be the corresponding tree.

**Comment by twoseventwo** [comment]
Strange. I can't replicate this at all on that tree, in 3.4.1 or 3.3.3. Is it possible you aren't using an up-to-date ggtree?

**Comment by KELEONUCSF** [comment]
I'm currently using ggtree version 1.8.1.


I've also noticed an issue trying to import the .tree output files into Geneious saying there is a problem with duplicate tips. Is there a way around this?

________________________________

**Comment by twoseventwo** [comment]
I'm not sure why this would happen if the BAMs have different names - @ChrisHIV ?

Stranger and stranger on the original issue - which OS are you on?

**Comment by ChrisHIV** [comment]
Hi Kristoffer, the format of the input tree is Newick, and that of the output tree is Nexus. I see a similar sounding Geneious error if I incorrectly tell it the output tree is Newick, but it imports fine as Nexus. Over to @twoseventwo for the length(lims) issue...

**Comment by tgolubch** [comment]
Does the tree file open in Figtree instead of Geneious?

**Comment by twoseventwo** [comment]
I'm still not able to replicate the length(lims) issue. Since it doesn't happen to me when everything is up-to-date, using trees which experienced it on other systems I'm assuming it's due to some combination of older package or R versions. For anyone experiencing it: if you can, please update everything and try again.

The -tn solution will work but may not be ideal for everyone.

**Comment by KELEONUCSF** [comment]
Hey all,

Thanks for the help! I'm currently on OSX 10.12.5. I have everything updated as well, and I can't seem to figure out the issue, but I'll keep tweaking things to see if I can get it to work! I agree it's most likely a combination of either older packages or R versions that are interrupting normal functioning.

Thanks for the help! the -tn solution works just fine for me!

**Comment by mdhall272** [comment]
I have finally identified and fixed this. It was caused by use of ggplot2 2.2.1.9000 (the most up-to-date GitHub version) rather than 2.2.1 (the CRAN version).
