### ISSUE TITLE
Error: length(lims) == 2 is not TRUE

### ISSUE THREAD

**Issue by antoine4ucsd** [BDI-pathogens/phyloscanner#13]
Hi
I am new in phyloscanner and I have been using it for multiple individuals and sliding windows of 200bp from Illumina.
I still need a lot of work to optimize the use of it but I was able to generate my first tree with **phyloscanner_make_trees.py**
I ran the following command:
`../phyloscanner_make_trees.py InputFileList.csv  --x-raxml '/Users/antoinechaillon/anaconda2/pkgs/raxml-8.2.10-0/bin/raxmlHPC-AVX2 -m GTRCAT -p 1 --no-seq-check' --windows 2200,2350,2500,2650,2800,2950,3100,3250,3400,3550 -A ../InfoAndInputs/3refs_HXB2.fasta --pairwise-align-to B.FR.83.HXB2_LAI_IIIB_BRU_K03455`

and it created 4 'best tree' output
<img width="339" alt="screen shot 2017-07-30 at 8 53 13 am" src="https://user-images.githubusercontent.com/18502631/28751303-8e0ec090-7504-11e7-98fa-846678ddb18a.png">

I would like now to test the next step and analyze with **phyloscanner_analyse_trees.R** but when I run the command below:
`../phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree. MyOutput s,0 -og B.FR.83.HXB2_LAI_IIIB_BRU_K03455 -m g`
I have the following:
`Warning: package ‘ggtree’ was built under R version 3.3.3
  |                                                  |   0%
Error: length(lims) == 2 is not TRUE
Execution halted`

Any clue about it? thanks and sorry for the 'basic' questions and possible lack of clarity. Let me know if you need more info and/or if you'd like me to share some data.

**Comment by twoseventwo** [comment]
Hi Antoine,

See issue #12 - I haven't been able to isolate this yet. A workaround is to use the -tn flag to produce Nexus rather than PDF trees.

What version of R, and OS, are you using? This is definitely a ggtree problem, so try to reinstall it to get rid of that "Warning: package ‘ggtree’ was built under R version 3.3.3" message.

Thanks, Matthew

**Comment by antoine4ucsd** [comment]
I really appreciate the fast response!
I am using R v 3.3.2  on Mac OS
I'm really excited about your tool, so I really want to get it working!

**Comment by twoseventwo** [comment]
If you're able to, try upgrading to 3.4.1 and updating all the packages. With everything up-to-date I don't get this problem. I'll see if I can reinstall an old version and track it down next week. In the meantime, try -tn.

**Comment by twoseventwo** [comment]
Closed as duplicate.

**Comment by antoine4ucsd** [comment]
Sure
thanks again!
I wish I will nice data to discuss with you soon
