### ISSUE TITLE
EstimateReadCountPerWindow.py IndexError

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#14]
Hi Chris,

I am getting the following error with using the script EstimatedReadCountPerWindow.py

`python2.7 tools/EstimateReadCountPerWindow.py InputFileList.csv
Now counting read and insert sizes for 25236
Traceback (most recent call last):
  File "tools/EstimateReadCountPerWindow.py", line 152, in <module>
    start = min(MappedPositions[0], MappedPositions[-1])
IndexError: list index out of range`

Any suggestions. I emailed a subset of reads.

Thanks,
Damien

**Comment by ChrisHIV** [comment]
Hi Damien, I haven't got your reads yet but I'm pretty sure what I just pushed will correct the bug. Pull and try again. Thanks for spotting!

**Comment by damientully** [comment]
Hi Chris,

Thanks for the speedy reply. It does produce .csv but 
`Now counting read and insert sizes for 25236
Info: 123 of 102722 reads in 2733.bam are flagged as being paired but don't have a mate present.
Traceback (most recent call last):
  File "tools/EstimateReadCountPerWindow.py", line 282, in <module>
    alias = aliases[(i - 1) % 2]
IndexError: list index out of range`

Damien

**Comment by ChrisHIV** [comment]
D'oh. Try again?

**Comment by damientully** [comment]
Wonderful! That worked! Produced both pdf and .csv.

Cheers,
Damien
