### ISSUE TITLE
Problem with running analysis script 

### ISSUE THREAD

**Issue by MarcNiebel** [BDI-pathogens/phyloscanner#23]
Hi,
I am struggling to run the analysis script for Phyloscanner after generating my trees. My input command is:

phyloscanner_analyse_trees.R third_iteration/trees_third_iteration/FastTree_  RunWithoutBlacklisting s,20 --outgroupName "1|a|AF009606" --tipRegex "^(.*)_([0-9]+)_read_([0-9]+)_count_([0-9]+)$" --normRefFileName branch_length_normalisation.csv_ByPosition.csv --multifurcationThreshold g --verbose

Below is the output:
Warning: replacing previous import ‘ggtree::getRoot’ by ‘phangorn::getRoot’ when loading ‘phyloscannerR’
Error in .stop(output, "parse error:") : parse error:
usage: ./phyloscanner_analyse_trees.R [-h] [-og OUTGROUPNAME]
                                      [-m MULTIFURCATIONTHRESHOLD]
                                      [-b USERBLACKLIST] [-od OUTPUTDIR] [-v]
                                      [-npb] [-x TIPREGEX] [-y FILENAMEREGEX]
                                      [-tfe TREEFILEEXTENSION]
                                      [-cfe CSVFILEEXTENSION] [-pw PDFWIDTH]
                                      [-ph PDFRELHEIGHT]
                                      [-psb PDFSCALEBARWIDTH] [-rda]
                                      [-sd SEED] [-ow] [-nr NORMREFFILENAME]
                                      [-ns] [-nc NORMALISATIONCONSTANTS]
                                      [-db DUPLICATEBLACKLIST]
                                      [-pbk PARSIMONYBLACKLISTK]
                                      [-rwt RAWBLACKLISTTHRESHOLD]
                                      [-rtt RATIOBLACKLISTTHRESHOLD] [-ub]

Calls: <Anonymous> -> res -> .stop
Execution halted

Any help would be much appreciated.

Marc

**Comment by mdhall272** [comment]
Hi Marc,

That's odd - I can't see anything obviously wrong with it. I presume your phyloscanner version is reasonably up to date? (If you update right now you'd need to change --verbose to --verbose 1 or --verbose 2, I made that change today.) Is it possible your shell is seeing special characters that need escaping - the pipes in the outgroup name maybe?

Thanks, Matthew

**Comment by MarcNiebel** [comment]
Hi Matthew,

Thanks for that tip. Worked with  --outgroupName  1\|a\|AF009606

Best Wishes,

Marc
