### ISSUE TITLE
Problem with first part of phyloscanner script

### ISSUE THREAD

**Issue by MarcNiebel** [BDI-pathogens/phyloscanner#25]
Hi Chris,

After a recent update I think you made in the first part of the script, I am getting an error which was not there previously for making the trees.

My command is: 

phyloscanner_make_trees.py P166_P63_test.csv --auto-window-params 250,0 --merge-paired-reads -A AF009606.fasta -2 1\|a\|AF009606 --no-tree -MTA 1 -MC 2 --time

The error is:

 Problem calling mafft. Quitting.
Traceback (most recent call last):
  File "../phyloscanner/phyloscanner_make_trees.py", line 851, in <module>
    '--preservecase', TempFileForPairwiseUnalignedRefs], stdout=f)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any thoughts would be much appreciated.

Kind Regards,

Marc

**Comment by ChrisHIV** [comment]
Hi Marc, sorry about that. Some versions of mafft (newer ones perhaps) result in the command 'linsi' being available as well as 'mafft'; I had thought all of them did. Will push a fix. In the mean time you can use the option "--x-mafft2 mafft" to stop phyloscanner trying to use linsi.

**Comment by MarcNiebel** [comment]
Hi Mathew,

Yea that resolved that problem but the next one is:

Error calling "pysam.AlignmentFile". The AlignmentFile attribute was introduced in pysam version 0.8.1; are you using an older version than that? You might be able to update by running
pip install pysam --upgrade
from the command line. Quitting.

Currently my python 2.7 has pysam 0.14 so am unable to understand what is required.

Kind Regards,

Marc

**Comment by MarcNiebel** [comment]
Hi Chris,

Yea that resolved that problem but the next one is:

Error calling "pysam.AlignmentFile". The AlignmentFile attribute was introduced in pysam version 0.8.1; are you using an older version than that? You might be able to update by running
pip install pysam --upgrade
from the command line. Quitting.

Currently my python 2.7 has pysam 0.14 so am unable to understand what is required.

Kind Regards,

Marc

**Comment by ChrisHIV** [comment]
Odd. Pull and try again: it won't fix it but should give more information.

**Comment by ChrisHIV** [comment]
Sorry the last commit contained a silly error, better now.

**Comment by MarcNiebel** [comment]
This is the error now:
Traceback (most recent call last):
  File "../phyloscanner/phyloscanner_make_trees.py", line 982, in <module>
    if hasattr(pysam, AlignmentFile):
NameError: name 'AlignmentFile' is not defined
Marc

**Comment by ChrisHIV** [comment]
Grr sorry try again.

**Comment by MarcNiebel** [comment]
After doing a bit of digging, it seems to be looking at an old pysam version (0.6) which explains why there seems to be an error. Now I need to figure out how to direct it to the 0.14 version instead.

**Comment by ChrisHIV** [comment]
I'm guessing you have at least two installations of python on your machine, each with a different version of pysam. The shebang at the top of phyloscanner_make_trees.py, #!/usr/bin/env python, means that if you run "phyloscanner_make_trees.py" it should use the same python as if you type "python" in your terminal. If you want to use a different version of python, e.g. the one started by /usr/bin/python2.foo, then you can either change the shebang or run the script with "/usr/bin/python2.foo phyloscanner_make_trees.py".

**Comment by MarcNiebel** [comment]
Actually I have three versions of python but only one version of python 2. This one has two pysam versions. The first is 0.6 and the second is 0.14. Python uses 0.6 which is why the error comes up. I have tried modifying the sys.path but again I am having no luck, even when modifying $PYTHONPATH variable in .bashrc. Will keep trying!

**Comment by MarcNiebel** [comment]
Resolved it by using a virtual environment :)
