### ISSUE TITLE
Problem with running second script

### ISSUE THREAD

**Issue by MarcNiebel** [BDI-pathogens/phyloscanner#28]
Hi Matthew,

I have a files of tree files which have been generated by FastTree. I am trying to use these in your script for analysing the trees. My command is:

../../../../../phyloscanner/phyloscanner_analyse_trees.R AlignedReadsInWindow_ P102_P110_multitrans s,20 --outgroupName AF009606  --allowMultiTrans --tipRegex "^(.*)_([0-9]+)_read_([0-9]+)_count_([0-9]+)$" --normRefFileName ../../../../1a_ORF.csv_ByPosition.csv --multifurcationThreshold g --verbose 2

The error I get is:

Warning: replacing previous import ‘ggtree::getRoot’ by ‘phangorn::getRoot’ when loading ‘phyloscannerR’
Random number seed is 197906578 
Error in phyloscanner.analyse.trees(tree.directory, tree.file.regex, reconstruction.mode,  : 
  unused arguments (verbosity, no.progress.bars)
Execution halted

Could you possible clarify which arguments are required. I am not sure I understand the error. Previous iterations of the above code worked fine.

Kind Regards,

Marc

**Comment by mdhall272** [comment]
Hi Marc,

Are the files beginning AlignedReadsInWindow_ tree files? And is there more than one of them?

This isn't anything you did - it's an internal function that's seeing the wrong arguments. I'm unclear why as yet.

**Comment by MarcNiebel** [comment]
Yes there are 50 of them which have the format:
AlignedReadsInWindow_1081_to_1260.tree (example)

**Comment by mdhall272** [comment]
What was different about the earlier iterations that worked?

**Comment by MarcNiebel** [comment]
Nothing except I did it about a month ago and recently updated the scripts

**Comment by MarcNiebel** [comment]
Do I just run it instead of normal script?

**Comment by mdhall272** [comment]
Yes. Github didn't like ".R" as a file extension, but it's just a modification of the same script.

**Comment by MarcNiebel** [comment]
Actually resolved it by re-installing the R package(phyloscannerR) without having to implement the debug version.
Thanks for your help.

Marc

**Comment by mdhall272** [comment]
This should probably be point one on the FAQ for problems with phyloscannerR! Thanks for letting me know.
