### ISSUE TITLE
Confusion of terminology "Trans" "Complex"

### ISSUE THREAD

**Issue by evandiego** [BDI-pathogens/phyloscanner#30]
Hi,

I am a little confused as to the meaning of trans, multi-trans and complex from the phyloscanner analyst trees program particularly in light of Thomas Leitner's papers on HIV. Are the ancestry types "Trans" equivalent to a combination of paraphyletic and polyphyletic (PP) while "multi-trans"  equivalent to paraphyletic–monophyletic (PM) and complex is not indicative of direct transmission?

Or is there a better way using these programs to flush out these terms?

Thank you in advance.
Evan

**Comment by mdhall272** [comment]
Hi Evan,

"Trans" is PM. PP can resolve to either "multi-trans" or "complex". The key is whether, once the ancestral state reconstruction is done, all the state (host) changes are in one direction. If, whenever the states at the two ends of a branch differ, the parent state is A and the child B, then the classification is "multi-trans". If there are some A to B branches and some B to A branches, then it is "complex".

Thanks, Matthew

**Comment by evandiego** [comment]
Thanks Matthew for this clarification.
