### ISSUE TITLE
Error with drawing simplified summary diagram

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#31]
Hi guys, 

I am using v1.6.0 and everything seems to run fine and I get a transmission summary file but I get the following error with drawing the simplified summary diagram:

`Error: Duplicate identifiers for rows (12, 23), (15, 25), (67, 74)`

Any ideas on what is causing the issue?
Damien

**Comment by mdhall272** [comment]
Hi Damien,

I'm not entirely sure what can be causing this - would it be possible for you to send me the transmission summary file, if it's not sensitive?

Thanks, Matthew

**Comment by damientully** [comment]
Just sent you an email with the file.

Thanks.
Damien

**Comment by mdhall272** [comment]
Hi Damien,

Thanks. That was just a typo in the 1.6.0 code which didn't cause errors when run on my example dataset, and very good to know about. Try pulling now?

**Comment by damientully** [comment]
That worked now. Thanks!
