### ISSUE TITLE
phyloscannerR no output when only 1 window/tree is used

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#38]
Hi guys,

When only one window is analyzed with phyloscanner_analyse_trees.R no pairwise relationship summary is printed or summary plot (a pdf is printed of the tree). I realize that this makes some sense as you may generally have multiple windows across a genome but what about if you had a single small amplicon across a region. While I could separate the amplicon into smaller windows I want to maximize the phylogenetic signal so is there a way to generate those files when only one tree is given.

Thanks
Damien

**Comment by mdhall272** [comment]
Hi Damien,

The reason for this is that both of those outputs are summaries across multiple windows which make little sense if you only have one. You can get the exact between-host relationships for the single tree using the --allClassifications and --collapsedTrees options.

(An alternative I recommend if you are doing a final analysis is to give phyloscanner_analyse_trees.R a set of bootstraps or posterior samples as input. This accounts for uncertainty in a different way.)

Thanks, Matthew

**Comment by damientully** [comment]
Hi Matthew,

Yes that what I figured but I will try those options that you suggested.

Thanks,
Damien
