### ISSUE TITLE
Problem with phyloscanner_analyse_trees.R

### ISSUE THREAD

**Issue by SteveKemp** [BDI-pathogens/phyloscanner#39]
Hi guys,

When running the second part of the analysis i.e. using phyloscanner_analyse_trees.R, following the online practical, when I run:

~/phyloscanner/phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree.InWindow_ \
RunWithoutBlacklisting s,20 --outgroupName C.BW.00.00BW07621.AF443088 \
--multifurcationThreshold g

I'm getting the following error:

Stevens-MacBook-Pro:MyTestDir steve$ ~/phyloscanner/phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree.InWindow_ RunWithoutBlacklisting s,20 --outgroupName C.BW.00.00BW07621.AF443088 --multifurcationThreshold g
Random number seed is 566921380 
Warning in initialise.phyloscanner(tree.file.directory, tree.file.regex,  :
  Attempting to guess a branch length threshold for multifurcations from the tree. Please visually examine the tree or trees for multifurcations before using the results of this analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 1000_to_1299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 2000_to_2299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 3000_to_3299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 4000_to_4299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 5000_to_5299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 6000_to_6299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 7000_to_7299 no non-blacklisted tips remain; this window will be removed from the analysis.
Warning in FUN(X[[i]], ...) :
  For tree ID 8000_to_8299 no non-blacklisted tips remain; this window will be removed from the analysis.
Error in phyloscanner.analyse.trees(tree.directory, tree.file.regex, reconstruction.mode,  : 
  All hosts have been blacklisted from all trees; nothing to do.
Execution halted

Any ideas on what's happening there?
Thanks,
Steve

**Comment by mdhall272** [comment]
Hi Steve,

Is this on your data, or on the sample data? My guess (if it's not the latter in which case it's clearly a bug and I should look ASAP) is that nothing in the tips actually matches the regex.

Matthew

**Comment by SteveKemp** [comment]
Hi Matthew,

This is on the included example/sample data, yes. I’ve made trees for my own data separately, but never tried the phyloscanner_analyse_trees.R myself, so I followed the online practical step-by-step to get used to it ☹

Thanks,
Steve

**Comment by mdhall272** [comment]
Ah, there was a file from the development branch that I really shouldn't have brought over in its entirety. Try pulling now?

**Comment by SteveKemp** [comment]
Hi Matthew,

Sorry I got distracted, I pulled from git and follow the instructions here: https://github.com/BDI-pathogens/phyloscanner/blob/master/InfoAndInputs/UpdatingPhyloscanner.sh

But when I run the install(“.”, dependencies = T), nothing happens. Is this the error – it’s not set up correctly on my mac?

Thanks,
Steve

**Comment by mdhall272** [comment]
Did literally nothing happen? No error messages or anything?

You could also try `install_github("BDI-pathogens/phyloscanner/phyloscannerR")`

**Comment by SteveKemp** [comment]
Yep, literally just hangs, no error.

I tried install_github("BDI-pathogens/phyloscanner/phyloscannerR") and similarly, just hanging. I could let you take a look via Zoom is you have time a little later? I feel like I’m just missing something really simple, but frustrating!

Thanks,
Steve

**Comment by mdhall272** [comment]
That's weird and it works fine for me. What version of R are you using? I'm happy to try Zoom if you show me how...

**Comment by SteveKemp** [comment]
Really strange!

I fixed the other error however, my mac had a corrupted gfortran install (don’t even know how!?), so the binaries weren’t compiling in R. That’s all fixed now however!

However, it doesn’t seem to have changed my issue with tip blacklisting. I’ll give this a go with some of my own data tomorrow and see what happens too! See attached .txt file?

Thanks,
Steve

**Comment by mdhall272** [comment]
That really seems like you aren't using the most up-to-date version. That bug is definitely fixed.

**Comment by SteveKemp** [comment]
V1.6.9?

**Comment by mdhall272** [comment]
I haven't actually put that fix in a numbered release, but if you download the current version it should be in (see https://github.com/BDI-pathogens/phyloscanner/commit/0527a4d3ff615d3f4d9bf1870911b6dcf26e928b)

**Comment by SteveKemp** [comment]
It was me being silly - I hadn't installed phyloscannerR after pulling from git (doh!)
