### ISSUE TITLE
analyse trees.R Error: evaluation nested too deeply: infinite recursion / options(expressions=)?

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#40]
Hi,

I seem to get the following error when using phyloscanner_analyse_trees.R on a dataset when performing the parsimony reconstruction: 

`Error: evaluation nested too deeply: infinite recursion / options(expressions=)?`
`Execution halted`
Any solutions?

Thanks,
Damien

**Comment by mdhall272** [comment]
Huh. Not seen that before. How many tips does the tree have?

**Comment by damientully** [comment]
A lot! ~20,000!

**Comment by mdhall272** [comment]
See https://stackoverflow.com/questions/22003021/explanation-of-r-optionsexpressions-to-non-computer-scientists - try <options(expressions=N)> for some large <N>?

**Comment by damientully** [comment]
Will take a look. Thanks

**Comment by damientully** [comment]
That worked. Thanks!
