### ISSUE TITLE
Seperate analyses or combined dataset

### ISSUE THREAD

**Issue by evandiego** [BDI-pathogens/phyloscanner#41]
Hello.

I am seeiking advice for running phyloscanner. I am a looking at a cohort of sequences where I have the donor and recipient. Would you suggest that I analyze each donor and recipient together in phyloscanner i.e. as a pair or should I analyze all of the data together i.e. as in the entire cohort combined as a single dataset? Have the authors noticed a difference in the results using the two methods?

Also in order to figure out the transmission direction is there a easy way or an easy summary that summarizes which is ancestral and whether the host changes are in one direction or what the earliest node corresponds to?

Thank you,

**Comment by mdhall272** [comment]
We haven't noticed a huge difference. In principle the inclusion of more samples in a single run should help with rooting. I would say that it's better to do combined runs unless that is going to be computationally prohibitive.

There are a number of outputs that will answer your second question. Are you using NGS data?

**Comment by evandiego** [comment]
Thank you for your reply. Yes I have NGS data. Illumina.

**Comment by mdhall272** [comment]
Hi, sorry for the delay. Look at the manual regarding the pairwise relationship summary in the first instance?

**Comment by evandiego** [comment]
Thanks Matthew for these patience. I have looked at the manual and perfromed the phyloscanner. However, most of my patients appear to have a "complex" relationship and when I go to figure out directionality I only get results from host1->host2 when I use the RScript called transmission summary.R. Is it possible to get direction when relationship is complex? How would I figure out the frequency of host2->host1 or equivocal? Does the program automatically collate the path12 and path21 over every window? Thank you.

**Comment by mdhall272** [comment]
Did you run phyloscanner_analyse_trees.R with --allowMultiTrans ?

**Comment by evandiego** [comment]
Yes I used the allowMultiTrans option.

**Comment by mdhall272** [comment]
That does suggest that you don't have a great signal of directionality. We call the "complex" topology when we aren't confident in the direction. Most likely the tips from the pair are very intermingled. I'm happy to have a look at the files if you like.
