### ISSUE TITLE
split_hosts_to_subgraphs.R Error: length(lims) == 2 is not TRUE

### ISSUE THREAD

**Issue by damientully** [BDI-pathogens/phyloscanner#42]
Hi Matthew,

I seem to be getting an error when running the split_hosts_to_subgraphs.R script. I am clearly doing something wrong:

> Getting tip read counts...
Identifying tips with hosts...
Constructing vector of hosts...
Finding tips for each host...
Finding MRCAs for each host...
Reconstructing internal node hosts with the Sankoff algorithm...
Calculating node costs...
Building full cost matrix...
  |==================================================| 100%
Reconstructing...
Identifying split hosts...
Writing output to file NEW/subgraphs_s_NEW.rda ...
Drawing tree...
Error: length(lims) == 2 is not TRUE
Execution halted

Any suggestions?

Thanks,
Damien

**Comment by mdhall272** [comment]
Hi Damien,

No, it's not you, it's us! Those scripts are rather elderly to be honest, and might very well go in a future release. But for now I've fixed it. You might do better in future to learn how to use phyloscannerR interactively, however. Running phyloscanner.analyse.tree (the R function, not the bash script) should do what you want.

**Comment by damientully** [comment]
Thanks. I normally would use run the phyloscanner.analyse.trees script but I am trying to get a pairwise_relationships.rda file for use in Phyloscanner.R.utilities and I think the only way to do so is to follow those steps as outlined in the Phyloscanner.R.utilities page as the current pipeline does not output this file (I think!)?

**Comment by mdhall272** [comment]
If you use -rda then you'll get an R image at the end which saves absolutely everything, so you just need to pluck what you need from that. Though I'm not sure how well that fits with Phyloscanner.R.utilities as it is now - what do you need from that? Much of that content has been moved across to the main repository.

**Comment by damientully** [comment]
Ah ok. I guess it was more to visualise the phylogenetic relationships between two individuals across the genome with the function phsc.plot.phyloscan which I guess one could pull that info out of the classification tables

**Comment by mdhall272** [comment]
There is a specific function in phyloscannerR called produce.pairwise.graphs. This admittedly isn't quite the same as Olli's version and I have been meaning to implement that as well.
