### ISSUE TITLE
PhyloscannerR error: Cannot normalise branch lengths from file without window cooardinates in tree IDs

### ISSUE THREAD

**Issue by magosil86** [BDI-pathogens/phyloscanner#50]
Hi Matthew,

I recently upgraded to v1.8.0 and tried the example dataset provided with phyloscannerR, however I am running into the following issue: 
`
Warning in initialise.phyloscanner(tree.file.directory, tree.file.regex,  :
  Cannot normalise branch lengths from file without window cooardinates in tree IDs (which are usually file suffixes); tree branch lengths will not be normalised.
`

Minimum working example:
Data:
[ptyr10_patients.txt](https://github.com/BDI-pathogens/phyloscanner/files/3334192/ptyr10_patients.txt)
[ptyr10_trees_newick.zip](https://github.com/BDI-pathogens/phyloscanner/files/3334194/ptyr10_trees_newick.zip)

call to phyloscanner_analyse_trees.R:
 `phyloscanner/phyloscanner_analyse_trees.R "ptyr10_trees_newick/" ptyr1 s,20 --allowMultiTrans --fileNameRegex "^\D*([0-9]+)_to_([0-9]+)\D*$" --maxReadsPerHost 50 --multifurcationThreshold 1e-05 --noProgressBars --normRefFileName "phyloscanner/phyloscannerR/inst/HIV_DistanceNormalisationOverGenome.csv" --normStandardiseGagPol --outgroupName "REF_CPX_AF460972" --outputRDA --overwrite --parsimonyBlacklistK 20 --ratioBlacklistThreshold 0 --rawBlacklistThreshold 20 --readCountsMatterOnZeroLengthBranches --relaxedAncestry --seed 42 --tipRegex "^(.*)_fq[0-9]+_read_([0-9]+)_count_([0-9]+)$" --verbose 1
`

Any suggestions?

Thanks

**Comment by mdhall272** [comment]
That ``--fileNameRegex`` doesn't work now, but the new default one does on that data.

**Comment by magosil86** [comment]
It works now, thanks for the tip Matthew!
