### ISSUE TITLE
Error installing phyloflows

### ISSUE THREAD

**Issue by dianatordoff** [BDI-pathogens/phyloscanner#55]
Reads:

_Error in get0(oNam, envir = ns) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1_

**Comment by mdhall272** [comment]
Before we look further, this looks at first glance like a quite generic R error - have you tried restarting R?
