### ISSUE TITLE
fail to install phyloscannerR from GitHub

### ISSUE THREAD

**Issue by BT896** [BDI-pathogens/phyloscanner#59]
Hi,

I'm getting an exit status after attempting installation of phyloscannerR to R 4.0.3. 
Install command is install_github("BDI-pathogens/phyloscanner/phyloscannerR", dependencies = T).

The error occurs at the same HTML link produce.pairwise.graphs2.

Error reads: 
C:../Local/Temp/RtmpEVaLHH/R.INSTALL434820413b15/phyloscannerR/man/produce.pairwise.graphs2.Rd:51: Bad \link text
* removing 'C:../Documents/R/win-library/4.0/phyloscannerR'
Error: Failed to install 'phyloscannerR' from GitHub:
  (converted from warning) installation of package ‘C:../Local/Temp/RtmpmkqZMh/file31603193268f/phyloscannerR_1.8.0.tar.gz’ had non-zero exit status

Is this something you've come across before?

Thanks,
Ben

**Comment by mdhall272** [comment]
I can't seem to replicate this but I don't have easy access to a Windows machine. I don't suppose updating roxygen2 helps?

**Comment by BT896** [comment]
I've updated roxygen2 but still comes up with the same error message at produce.pairwise.graphs2.Rd:51. 

Should '\link{\code{classify.pairwise.relationships}}' read '\code{\link{classify.pairwise.relationships}} ?

**Comment by mdhall272** [comment]
Seems unlikely to me - like I say, this works fine on a Mac. Try cloning the repository any using `install`?

**Comment by BT896** [comment]
Deleted @seealso and now fully installed. Thanks for your help!

**Comment by mdhall272** [comment]
Was it just that `@seealso`, or all of them?

**Comment by BT896** [comment]
Just that one
