### ISSUE TITLE
Problems running phyloscanner_analyse_trees.R

### ISSUE THREAD

**Issue by thednainus** [BDI-pathogens/phyloscanner#62]
Hello,

I am doing the tutorial [here](https://drive.google.com/drive/folders/0BwygWUC73hnxbGtHSFpWdzYzVkk) and I get an error message when running the code below:

**Code**
```
~/phyloscanner/phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree.InWindow_  
RunWithoutBlacklisting s,20 --outgroupName C.BW.00.00BW07621.AF443088  
--multifurcationThreshold g
```

**Error message:**
```
Error in DataMask$new(.data, caller_env) : 
  argument "caller_env" is missing, with no default
Calls: sapply ... mutate.data.frame -> mutate_cols -> <Anonymous> -> initialize
Execution halted
```

I did find some similar error message in google (https://www.gitmemory.com/issue/YuLab-SMU/ggtree/395/836076062).
And indeed my `dplyr` and `ggtree` is the same version as in the google search.

I use a mac OS 10.3.6. My R version is 4.0.3
`dplyr` version is 1.0.6 and `ggtree` version is 2.4.2

Is the error message caused by the new `dplyr` version or is it something else?

Thanks!
Fabricia.

**Comment by mdhall272** [comment]
If you update to R 4.1.0 and the latest ggtree, it runs fine on my machine.

**Comment by thednainus** [comment]
Hi Matthew, it did run in my computer too when I updated to R 4.1.0. Thanks. I just get a few warning messages. Do you get those too? (I still get the results).

**Comment by mdhall272** [comment]
Have you updated phyloscanner? I got rid of a lot of the warnings last night.

**Comment by thednainus** [comment]
Just updated it now. No more warnings. Thanks!
