### ISSUE TITLE
Cannot install Phyloscanner.R.utilities

### ISSUE THREAD

**Issue by vtsyvina** [BDI-pathogens/phyloscanner#66]
When I'm trying to run the tool on example data set by running this command:
`~/phyloscanner/phyloscanner_analyse_trees.R RAxMLfiles/RAxML_bestTree. MyOutput s,12.5 --outgroupName C.BW.00.00BW07621.AF443088 --multifurcationThreshold g
`

I get the following error:
`Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘phyloscannerR’
Random number seed is 488431526
Error in phyloscanner.analyse.trees(tree.directory, tree.file.regex, reconstruction.mode,  :
  could not find function "phyloscanner.analyse.trees"
Execution halted
`

When I try to run 
`./phyloscannerR/phyloscanner_installation.sh`

I get this:
```
`> options(unzip = "internal");library(devtools);devtools::install_github("olli0601/Phyloscanner.R.utilities")
Loading required package: usethis
Downloading GitHub repo olli0601/Phyloscanner.R.utilities@HEAD

Skipping 3 packages not available: RBGL, Rsamtools, ggtree
   checking for file ‘/alina-data1/tmp/Rtmp3A8vhb/remotes2a7a2112ccf0f/olli0601-Phyloscanner.R.utilities-36d3269/DESCRIPTION’ ✔  checking for file ‘/alina-data1/tmp/Rtmp3A8vhb/remotes2a7a2112ccf0f/olli0601-Phyloscanner.R.utilities-36d3269/DESCRIPTION’ (429ms)
─  preparing ‘Phyloscanner.R.utilities’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘Phyloscanner.R.utilities_0.7-1.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘Phyloscanner.R.utilities/misc_data_analysis_RCCS1519/Rk1519_02_make_potential_transmission_networks.R’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘Phyloscanner.R.utilities/vignettes/figures/phsc_analysis_of_dataset_S1_phyloscan_RkA04565F_RkA05315F.png’

Installing package into ‘/home/vtsivina/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘Phyloscanner.R.utilities’ ...
** using non-staged installation via StagedInstall field
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
Execution halted
ERROR: lazy loading failed for package ‘Phyloscanner.R.utilities’
* removing ‘/home/vtsivina/R/x86_64-pc-linux-gnu-library/3.6/Phyloscanner.R.utilities’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp3A8vhb/file2a7a23ff33ccc/Phyloscanner.R.utilities_0.7-1.tar.gz’ had non-zero exit status`
```

Seems like some conflict of versions from googling. Can you give me a tip on how to resolve all the dependencies? Also I had to manually install RBGL cause script couldn't do it. 
I activated the "phylo" conda environment created by the script, but it doesn't help.

Also, not sure where to get the documentation on installation of the tool. The GitHub  READ.me page doesn't seem to have much directions. Maybe I'm missing something?

Thanks

**Comment by mdhall272** [comment]
@vtsyvina Please ignore phyloscanner_installation.sh - it's not part of the standard installation pathway. (@XiaoyueXI could you review if this file is necessary for the public repository and remove it if not?) The installation instructions that @ChrisHIV outlines above should work.

**Comment by vtsyvina** [comment]
@ChrisHIV still got the same error. I'll switch to Virtualbox. It seems to work.

**Comment by mdhall272** [comment]
@vtsyvina Is it literally the same error? The file @ChrisHIV pointed to doesn't use Phyloscanner.R.utilities at all.

**Comment by mdhall272** [comment]
Huh. Since sudo is using a different binary, you might not actually be trying to install phyloscannerR somewhere you can use it! You shouldn't really need to use that script with `sudo` if you know what you're doing, for what it's worth. You need to install ggtree from bioconductor (https://bioconductor.org/packages/release/bioc/html/ggtree.html) and then you can use `devtools::install` on the phyloscannerR directory or `devtools::install_github` on the phyloscannerR relevant folder of this repository.
