### ISSUE TITLE
Installing phyloflows

### ISSUE THREAD

**Issue by mmaninetti** [BDI-pathogens/phyloscanner#69]
Good morning,

I am trying to install phyloflows on R, and I am encountering some problems. I have tried both to install it from github, and to download the folder and install it on R locally, but I always get the same problem:
*** installing help indices
  converting help for package 'phyloflows'
    finding HTML links ... done
    source.attribution.mcmc                 html  
Errore: C:/Users/dalma/AppData/Local/Temp/RtmpemQqU6/Rbuild583424ec3766/phyloflows/man/source.attribution.mcmc.Rd:70: Bad \link text
Can I please ask if you have any idea of how I can make it work? Thank you really much

**Comment by olli0601** [comment]
Hi @mmaninetti 

Uh that s weird. Try from the command line using `R CMD INSTALL --no-docs`?

@XiaoyueXI you are probably the best person to help here.

Best wishes,
olli

**Comment by XiaoyueXI** [comment]
Hello both, I tried to install phyloflows from git on a mac laptop just now where phyloflows was never installed. And it seems to be successful. I do not have a windows machine to try. But I will message @mmaninetti to discuss this further.

**Comment by mmaninetti** [comment]
Dear Olli,

Thanks for the suggestion. I had already tried R cmd install, I will try it
again later.

Best regards,
Marco Maninetti

Il lun 7 nov 2022, 11:45 Oliver ***@***.***> ha scritto:

**Comment by XiaoyueXI** [comment]
issues solved
