### ISSUE TITLE
Couldn't compile software using "make" command

### ISSUE THREAD

**Issue by manisenthils** [BDI-pathogens/phyloscanner#74]
Hello people, I have been downloading and installing all the necessary tools and software one by one using the Phyloscanner installation notes. Now I got an error in the  "make" command. I tried solving it by searching for "nadd '' variable in several files. And tried exporting it and deleting that line manually but nothing got me out of this!!! I pasted the error  bellow . I hope someone can give me the solution!

/usr/include/features.h:194:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  194 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
gcc -o makedirectionlist mtxutl.o io.o mltaln9.o tddis.o constants.o partSalignmm.o Lalignmm.o rna.o Salignmm.o  Dalignmm.o Falign.o Falign_localhom.o Galign11.o Lalign11.o genalign11.o SAalignmm.o MSalignmm.o makedirectionlist.o defs.o fft.o fftFunctions.o addfunctions.o  -Denablemultithread  -std=c99 -O3  -lm  -lpthread
/usr/bin/ld: defs.o:(.bss+0x4): multiple definition of `nadd'; makedirectionlist.o:(.bss+0x10): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:203: makedirectionlist] Error 1

**Comment by ChrisHIV** [comment]
> Now I got an error in the "make" command
For which software? (Note that installing each separate piece of software that phyloscanner requires is not the same as 'installing phyloscanner'.) I haven't seen that error before. If googling it doesn't help you, perhaps the authors of whichever software you are trying to `make` can advise.
